---
- hosts: hadoop-nodes
  tasks:
    - name: adding user hadoop
      user:
        name: hadoop
    - name: create directories for hdfs and change permissions
      file:
        path: /data1/dfs
        state: directory
        owner: hadoop
        group: hadoop
        mode: 0755
    - name: create directories for hdfs and change permissions
      file:
        path: /data2/dfs
        state: directory
        owner: hadoop
        group: hadoop
        mode: 0755
    - name: check the jdk 1.8
      yum:
        name: java-1.8.0-openjdk-devel
    - name: Unarchiving the hadoop libraries
      unarchive:
        src: https://www-us.apache.org/dist/hadoop/common/hadoop-3.0.0/hadoop-3.0.0.tar.gz
        dest: /opt
        remote_src: yes
        owner: hadoop
        group: hadoop
    - name: update the hadoop profile
      lineinfine: 
        dest: /home/hadoop/.bash_profile
        state: present
        line: 'export PATH=$PATH:/opt/hadoop-3.0.0/bin:/opt/hadoop-3.0.0/sbin'
    - name: update JAVA_HOME in profile
      lineinfine:
        dest: /home/hadoop/.bash_profile
        state: present
        line: 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.171-8.b10.e17_5.x86_6'
    - name: update HADOOP_CONF_DIR in profile
      lineinfine:
        dest: /home/hadoop/.bash_profile
        state: present
        line: 'export HADOOP_CONF_DIR=/etc/hadoop/conf'
    - name: create /var/log/hadoop 
      file:
        path: /var/log/hadoop
        state: directory
        owner: hadoop
        group: hadoop
        mode: 0755
    - name: update the log dir in profile
      lineinfine:
        dest: /home/hadoop/.bash_profile
        state: present
        line: 'export HADOOP_LOG_DIR=/var/log/hadoop'